name: produk
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  intl: ^0.17.0
  group_radio_button: ^1.3.0
  dropdown_button2: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
